In [1]:
from pathlib import Path

resources_path = Path("tests/")
input_file_name = "parameters.txt"
meteorological_file_name = "dados2022.xlsx"
input_file = resources_path / input_file_name
meteorological_file = resources_path / meteorological_file_name

In [5]:
import pandas as pd
import numpy as np
from simulatrigo import tools

met_data = pd.read_excel(meteorological_file)
met_data['mean_temp'] = (met_data['min_temp'] + met_data['max_temp']) / 2
param = tools.Parameters(*np.loadtxt(input_file, dtype=float))

In [3]:
from datetime import datetime, timedelta

def day_of_year_to_date(year, day_of_year):
    """
    Converte um dia do ano para uma data no formato dd/mm/yyyy.
    
    :param year: Ano (ex: 2025)
    :param day_of_year: Dia do ano (1 a 365 ou 366)
    :return: Data no formato dd/mm/yyyy
    """
    start_of_year = datetime(year, 1, 1)  # Primeiro dia do ano
    date = start_of_year + timedelta(days=day_of_year - 1)  # Adiciona os dias
    return date.strftime("%d/%m/%Y")  # Retorna no formato desejado

In [4]:
from simulatrigo import model
from IPython.display import display, HTML

cultivar_name = {
    1: "senna",
    2: "astro",
    3: "calibre",
    4: "audaz",
    5: "duque",
    6: "trunfo",
    7: "agile",
    8: "feroz",
    9: "aton",
    10: "toruk",
    11: "1403",
    12: "premium",
    13: "ponteiro",
    14: "superprecoce",
    15: "precoce",
    16: "medio",
    17: "tardio"
}

model.configure()
results = []
for i in range(1, 18):
    param.name_cultivar = i
    cultivar_results = []
    for data in [154, 208]:
        param.sowing_day = data
        result: dict = model.run(parameters=param, meteorological_table=met_data)
        cultivar_results.append({
            "Semeadura": day_of_year_to_date(2022, data),
            "Emergencia": day_of_year_to_date(2022, result.get("result_list")[0] + data),
            "Perfilhamento": day_of_year_to_date(2022, result.get("result_list")[1] + data),
            "Duplo Anel": day_of_year_to_date(2022, result.get("result_list")[2] + data),
            "Espigueta terminal": day_of_year_to_date(2022, result.get("result_list")[3] + data),
            "Elongação do Colmo": day_of_year_to_date(2022, result.get("result_list")[4] + data),
            "Folha Bandeira": day_of_year_to_date(2022, result.get("result_list")[5] + data),
            "Emborrachamento": day_of_year_to_date(2022, result.get("result_list")[6] + data),
            "Florecimento": day_of_year_to_date(2022, result.get("result_list")[7] + data),
            "Maturidade": day_of_year_to_date(2022, result.get("result_list")[8] + data),
        })
    # Criar um DataFrame para o cultivar atual
    cultivar_df = pd.DataFrame(cultivar_results)
    
    # Exibir a tabela com um título
    nome = cultivar_name.get(i)
    display(HTML(f"<h3>Cultivar {nome}</h3>"))
    display(cultivar_df)

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,29/06/2022,29/06/2022,06/07/2022,15/07/2022,27/07/2022,03/08/2022,15/08/2022,27/09/2022
1,27/07/2022,04/08/2022,21/08/2022,21/08/2022,28/08/2022,08/09/2022,20/09/2022,27/09/2022,06/10/2022,05/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,29/06/2022,04/07/2022,12/07/2022,21/07/2022,02/08/2022,12/08/2022,25/08/2022,07/10/2022
1,27/07/2022,04/08/2022,21/08/2022,26/08/2022,05/09/2022,11/09/2022,25/09/2022,01/10/2022,13/10/2022,11/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,28/06/2022,02/07/2022,10/07/2022,18/07/2022,29/07/2022,08/08/2022,24/08/2022,05/10/2022
1,27/07/2022,04/08/2022,19/08/2022,24/08/2022,02/09/2022,09/09/2022,23/09/2022,30/09/2022,12/10/2022,11/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,05/07/2022,15/07/2022,23/07/2022,08/08/2022,16/08/2022,31/08/2022,14/10/2022
1,27/07/2022,04/08/2022,22/08/2022,27/08/2022,07/09/2022,14/09/2022,30/09/2022,06/10/2022,18/10/2022,16/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,05/07/2022,15/07/2022,23/07/2022,05/08/2022,15/08/2022,28/08/2022,12/10/2022
1,27/07/2022,04/08/2022,22/08/2022,26/08/2022,07/09/2022,14/09/2022,28/09/2022,05/10/2022,16/10/2022,14/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,05/07/2022,15/07/2022,23/07/2022,05/08/2022,15/08/2022,28/08/2022,12/10/2022
1,27/07/2022,04/08/2022,22/08/2022,26/08/2022,07/09/2022,14/09/2022,28/09/2022,05/10/2022,16/10/2022,14/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,01/07/2022,05/07/2022,15/07/2022,23/07/2022,06/08/2022,15/08/2022,28/08/2022,12/10/2022
1,27/07/2022,04/08/2022,22/08/2022,27/08/2022,07/09/2022,14/09/2022,29/09/2022,05/10/2022,17/10/2022,15/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,01/07/2022,05/07/2022,15/07/2022,23/07/2022,04/08/2022,14/08/2022,27/08/2022,12/10/2022
1,27/07/2022,04/08/2022,23/08/2022,27/08/2022,08/09/2022,15/09/2022,28/09/2022,05/10/2022,16/10/2022,15/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,04/07/2022,14/07/2022,23/07/2022,10/08/2022,18/08/2022,02/09/2022,16/10/2022
1,27/07/2022,04/08/2022,22/08/2022,26/08/2022,06/09/2022,14/09/2022,01/10/2022,07/10/2022,20/10/2022,18/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,01/07/2022,05/07/2022,16/07/2022,24/07/2022,12/08/2022,19/08/2022,03/09/2022,16/10/2022
1,27/07/2022,04/08/2022,23/08/2022,27/08/2022,08/09/2022,16/09/2022,02/10/2022,08/10/2022,20/10/2022,18/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,01/07/2022,05/07/2022,16/07/2022,24/07/2022,12/08/2022,19/08/2022,03/09/2022,16/10/2022
1,27/07/2022,04/08/2022,23/08/2022,27/08/2022,08/09/2022,16/09/2022,02/10/2022,08/10/2022,20/10/2022,18/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,05/07/2022,15/07/2022,23/07/2022,10/08/2022,18/08/2022,02/09/2022,16/10/2022
1,27/07/2022,04/08/2022,22/08/2022,27/08/2022,07/09/2022,15/09/2022,01/10/2022,08/10/2022,20/10/2022,18/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,02/07/2022,06/07/2022,18/07/2022,25/07/2022,15/08/2022,25/08/2022,09/09/2022,21/10/2022
1,27/07/2022,04/08/2022,24/08/2022,28/08/2022,09/09/2022,18/09/2022,06/10/2022,14/10/2022,25/10/2022,23/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,28/06/2022,03/07/2022,11/07/2022,21/07/2022,01/08/2022,11/08/2022,25/08/2022,06/10/2022
1,27/07/2022,04/08/2022,20/08/2022,25/08/2022,04/09/2022,09/09/2022,24/09/2022,01/10/2022,12/10/2022,11/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,01/07/2022,05/07/2022,15/07/2022,23/07/2022,06/08/2022,15/08/2022,28/08/2022,12/10/2022
1,27/07/2022,04/08/2022,22/08/2022,27/08/2022,07/09/2022,14/09/2022,29/09/2022,05/10/2022,17/10/2022,15/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,30/06/2022,05/07/2022,15/07/2022,23/07/2022,10/08/2022,18/08/2022,02/09/2022,16/10/2022
1,27/07/2022,04/08/2022,22/08/2022,27/08/2022,07/09/2022,15/09/2022,01/10/2022,08/10/2022,20/10/2022,18/11/2022

,Semeadura,Emergencia,Perfilhamento,Duplo Anel,Espigueta terminal,Elongação do Colmo,Folha Bandeira,Emborrachamento,Florecimento,Maturidade
0,03/06/2022,11/06/2022,02/07/2022,06/07/2022,18/07/2022,25/07/2022,15/08/2022,25/08/2022,09/09/2022,21/10/2022
1,27/07/2022,04/08/2022,24/08/2022,28/08/2022,09/09/2022,18/09/2022,06/10/2022,14/10/2022,25/10/2022,23/11/2022